services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: platziflix_user
      POSTGRES_PASSWORD: platziflix_password
      POSTGRES_DB: platziflix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U platziflix_user -d platziflix"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    build: .
    command: ["./scripts/init_db.sh"]
    volumes:
      - ./app:/app/app
      - ./specs:/app/specs
      - ./scripts:/app/scripts
    environment:
      - DATABASE_URL=postgresql://platziflix_user:platziflix_password@db:5432/platziflix
      - ENVIRONMENT=development
      - DEBUG=true
      - POSTGRES_USER=platziflix_user
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./specs:/app/specs
    environment:
      - DATABASE_URL=postgresql://platziflix_user:platziflix_password@db:5432/platziflix
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  postgres_data:
