version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: platziflix_user
      POSTGRES_PASSWORD: platziflix_password
      POSTGRES_DB: platziflix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U platziflix_user -d platziflix"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql://platziflix_user:platziflix_password@db:5432/platziflix
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
