"""Initial migration: create teachers, courses, lectures, and course_teacher tables

Revision ID: 7645eb2d5dc0
Revises: 
Create Date: 2025-07-12 23:41:10.260555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7645eb2d5dc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_deleted_at', 'courses', ['deleted_at'], unique=False)
    op.create_index('idx_courses_slug_deleted_at', 'courses', ['slug', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teachers_deleted_at', 'teachers', ['deleted_at'], unique=False)
    op.create_index('idx_teachers_email_deleted_at', 'teachers', ['email', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_table('course_teacher',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'teacher_id')
    )
    op.create_index('idx_course_teacher_course_id', 'course_teacher', ['course_id'], unique=False)
    op.create_index('idx_course_teacher_teacher_id', 'course_teacher', ['teacher_id'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lectures_course_id', 'lectures', ['course_id'], unique=False)
    op.create_index('idx_lectures_course_id_deleted_at', 'lectures', ['course_id', 'deleted_at'], unique=False)
    op.create_index('idx_lectures_deleted_at', 'lectures', ['deleted_at'], unique=False)
    op.create_index('idx_lectures_slug', 'lectures', ['slug'], unique=False)
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_index(op.f('ix_lectures_slug'), 'lectures', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectures_slug'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.drop_index('idx_lectures_slug', table_name='lectures')
    op.drop_index('idx_lectures_deleted_at', table_name='lectures')
    op.drop_index('idx_lectures_course_id_deleted_at', table_name='lectures')
    op.drop_index('idx_lectures_course_id', table_name='lectures')
    op.drop_table('lectures')
    op.drop_index('idx_course_teacher_teacher_id', table_name='course_teacher')
    op.drop_index('idx_course_teacher_course_id', table_name='course_teacher')
    op.drop_table('course_teacher')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_index('idx_teachers_email_deleted_at', table_name='teachers')
    op.drop_index('idx_teachers_deleted_at', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index('idx_courses_slug_deleted_at', table_name='courses')
    op.drop_index('idx_courses_deleted_at', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
